# =============================================================================
# AWS Sandbox - Taskfile for External Users
# =============================================================================
# Simple commands to use aws-sandbox npm package
# Install: npm install -g aws-sandbox
# Docs: https://www.npmjs.com/package/aws-sandbox
# =============================================================================

version: '3'

vars:
  VERSION: "0.2.6"
  EVIDENCE_DIR: "/workspace/tmp/aws-sandbox"

tasks:
  default:
    desc: Show available commands
    cmds:
      - |
        echo "AWS Sandbox v{{.VERSION}} - Quick Start"
        echo "========================================"
        echo ""
        echo "Commands:"
        echo "  task install    Install aws-sandbox from npm"
        echo "  task test       Run Tier 1+2 tests (free)"
        echo "  task deploy     Deploy to LocalStack"
        echo "  task upgrade    Upgrade to latest version"
        echo ""
        echo "Usage:"
        echo "  aws-sandbox --help"
        echo "  aws-sandbox test --tier=1"
        echo "  aws-sandbox deploy --localstack"

  install:
    desc: Install aws-sandbox from npm
    cmds:
      - npm install -g aws-sandbox@{{.VERSION}} --ignore-scripts
      - aws-sandbox --version

  test:
    desc: Run Tier 1+2 tests (free, no AWS credentials)
    cmds:
      - aws-sandbox test --tier=1
      - aws-sandbox test --tier=2

  test:tier1:
    desc: Run Tier 1 snapshot tests only
    cmds:
      - aws-sandbox test --tier=1

  test:tier2:
    desc: Run Tier 2 LocalStack tests only
    cmds:
      - aws-sandbox test --tier=2

  deploy:
    desc: Deploy to LocalStack (requires source code - see output for options)
    cmds:
      - aws-sandbox deploy --localstack

  upgrade:
    desc: Upgrade to latest version
    cmds:
      - npm install -g aws-sandbox@latest --ignore-scripts
      - aws-sandbox --version

  help:
    desc: Show aws-sandbox help
    cmds:
      - aws-sandbox --help

  evidence:generate:
    desc: Generate validation evidence (actual execution, not instructions)
    cmds:
      - |
        echo "=== AWS Sandbox Evidence Generation ==="
        echo "Version: {{.VERSION}}"
        echo "Timestamp: $(date -Iseconds)"
        echo ""

        # Create evidence directory
        mkdir -p {{.EVIDENCE_DIR}}

        # 1. CLI Version Evidence
        echo "1. Capturing CLI version..."
        aws-sandbox --version > {{.EVIDENCE_DIR}}/01-version.txt 2>&1
        cat {{.EVIDENCE_DIR}}/01-version.txt

        # 2. Tier 1 Test Evidence
        echo ""
        echo "2. Running Tier 1 test..."
        aws-sandbox test --tier=1 2>&1 | tee {{.EVIDENCE_DIR}}/02-tier1-test.txt

        # 3. Tier 2 Test Evidence (LocalStack connectivity)
        echo ""
        echo "3. Running Tier 2 test..."
        aws-sandbox test --tier=2 2>&1 | tee {{.EVIDENCE_DIR}}/03-tier2-test.txt

        # 4. LocalStack Health Check
        echo ""
        echo "4. LocalStack health check..."
        curl -sf http://localstack:4566/_localstack/health > {{.EVIDENCE_DIR}}/04-localstack-health.json 2>&1 || echo '{"error": "LocalStack not reachable"}' > {{.EVIDENCE_DIR}}/04-localstack-health.json
        cat {{.EVIDENCE_DIR}}/04-localstack-health.json

        # 5. Generate Summary
        echo ""
        echo "5. Generating summary..."
        cat > {{.EVIDENCE_DIR}}/05-summary.md << EOF
        # AWS Sandbox Evidence Report

        **Generated**: $(date -Iseconds)
        **Version**: {{.VERSION}}
        **Mode**: Consumer (npm package)

        ## Test Results

        | Test | Status | Evidence |
        |------|--------|----------|
        | CLI Version | $(grep -q "{{.VERSION}}" {{.EVIDENCE_DIR}}/01-version.txt && echo "PASS" || echo "FAIL") | 01-version.txt |
        | Tier 1 | $(grep -q "PASSED" {{.EVIDENCE_DIR}}/02-tier1-test.txt && echo "PASS" || echo "FAIL") | 02-tier1-test.txt |
        | Tier 2 | $(grep -q "PASSED" {{.EVIDENCE_DIR}}/03-tier2-test.txt && echo "PASS" || echo "FAIL") | 03-tier2-test.txt |
        | LocalStack | $(grep -q "running" {{.EVIDENCE_DIR}}/04-localstack-health.json && echo "PASS" || echo "N/A") | 04-localstack-health.json |

        ## Files

        \`\`\`
        $(ls -la {{.EVIDENCE_DIR}}/)
        \`\`\`
        EOF

        echo ""
        echo "=== Evidence Generated ==="
        echo "Directory: {{.EVIDENCE_DIR}}/"
        ls -la {{.EVIDENCE_DIR}}/
        echo ""
        echo "Summary: {{.EVIDENCE_DIR}}/05-summary.md"
